// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DatabaseService.proto
// Protobuf Java Version: 4.28.3

package io.grpc.dbserver;

public final class DatabaseServiceOuterClass {
  private DatabaseServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DatabaseServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RPC_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPC_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RPC_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPC_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DatabaseService.proto\"j\n\013RPC_Request\022\035" +
      "\n\toperation\030\001 \001(\0162\n.Operation\022\022\n\005Index\030\002" +
      " \001(\005H\000\210\001\001\022\023\n\006Record\030\003 \001(\tH\001\210\001\001B\010\n\006_Index" +
      "B\t\n\007_Record\"=\n\014RPC_Response\022\016\n\006record\030\001 " +
      "\001(\t\022\014\n\004size\030\002 \001(\005\022\017\n\007success\030\003 \001(\010*F\n\tOp" +
      "eration\022\013\n\007DEFAULT\020\000\022\016\n\nGET_RECORD\020\001\022\016\n\n" +
      "ADD_RECORD\020\002\022\014\n\010GET_SIZE\020\0032B\n\017DatabaseSe" +
      "rvice\022/\n\020PerformOperation\022\014.RPC_Request\032" +
      "\r.RPC_ResponseB\024\n\020io.grpc.dbserverP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RPC_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RPC_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RPC_Request_descriptor,
        new java.lang.String[] { "Operation", "Index", "Record", });
    internal_static_RPC_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RPC_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RPC_Response_descriptor,
        new java.lang.String[] { "Record", "Size", "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
