// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dbServer.proto
// Protobuf Java Version: 4.28.3

package io.grpc.dbserver;

/**
 * Protobuf type {@code RPC_Response}
 */
public final class RPC_Response extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:RPC_Response)
    RPC_ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      RPC_Response.class.getName());
  }
  // Use RPC_Response.newBuilder() to construct.
  private RPC_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RPC_Response() {
    record_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.dbserver.DbServer.internal_static_RPC_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.dbserver.DbServer.internal_static_RPC_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.dbserver.RPC_Response.class, io.grpc.dbserver.RPC_Response.Builder.class);
  }

  public static final int RECORD_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object record_ = "";
  /**
   * <pre>
   * Holds the record data for getRecord
   * </pre>
   *
   * <code>string record = 1;</code>
   * @return The record.
   */
  @java.lang.Override
  public java.lang.String getRecord() {
    java.lang.Object ref = record_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      record_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Holds the record data for getRecord
   * </pre>
   *
   * <code>string record = 1;</code>
   * @return The bytes for record.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordBytes() {
    java.lang.Object ref = record_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      record_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 2;
  private int size_ = 0;
  /**
   * <pre>
   * Holds the size data for getSize
   * </pre>
   *
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int SUCCESS_FIELD_NUMBER = 3;
  private boolean success_ = false;
  /**
   * <pre>
   * Indicates success for addRecord operation
   * </pre>
   *
   * <code>bool success = 3;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(record_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, record_);
    }
    if (size_ != 0) {
      output.writeInt32(2, size_);
    }
    if (success_ != false) {
      output.writeBool(3, success_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(record_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, record_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, size_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, success_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.dbserver.RPC_Response)) {
      return super.equals(obj);
    }
    io.grpc.dbserver.RPC_Response other = (io.grpc.dbserver.RPC_Response) obj;

    if (!getRecord()
        .equals(other.getRecord())) return false;
    if (getSize()
        != other.getSize()) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORD_FIELD_NUMBER;
    hash = (53 * hash) + getRecord().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.dbserver.RPC_Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.grpc.dbserver.RPC_Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.grpc.dbserver.RPC_Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.dbserver.RPC_Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.dbserver.RPC_Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RPC_Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RPC_Response)
      io.grpc.dbserver.RPC_ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.dbserver.DbServer.internal_static_RPC_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.dbserver.DbServer.internal_static_RPC_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.dbserver.RPC_Response.class, io.grpc.dbserver.RPC_Response.Builder.class);
    }

    // Construct using io.grpc.dbserver.RPC_Response.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      record_ = "";
      size_ = 0;
      success_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.dbserver.DbServer.internal_static_RPC_Response_descriptor;
    }

    @java.lang.Override
    public io.grpc.dbserver.RPC_Response getDefaultInstanceForType() {
      return io.grpc.dbserver.RPC_Response.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.dbserver.RPC_Response build() {
      io.grpc.dbserver.RPC_Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.dbserver.RPC_Response buildPartial() {
      io.grpc.dbserver.RPC_Response result = new io.grpc.dbserver.RPC_Response(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.grpc.dbserver.RPC_Response result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.record_ = record_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.dbserver.RPC_Response) {
        return mergeFrom((io.grpc.dbserver.RPC_Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.dbserver.RPC_Response other) {
      if (other == io.grpc.dbserver.RPC_Response.getDefaultInstance()) return this;
      if (!other.getRecord().isEmpty()) {
        record_ = other.record_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              record_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              success_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object record_ = "";
    /**
     * <pre>
     * Holds the record data for getRecord
     * </pre>
     *
     * <code>string record = 1;</code>
     * @return The record.
     */
    public java.lang.String getRecord() {
      java.lang.Object ref = record_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        record_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Holds the record data for getRecord
     * </pre>
     *
     * <code>string record = 1;</code>
     * @return The bytes for record.
     */
    public com.google.protobuf.ByteString
        getRecordBytes() {
      java.lang.Object ref = record_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        record_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Holds the record data for getRecord
     * </pre>
     *
     * <code>string record = 1;</code>
     * @param value The record to set.
     * @return This builder for chaining.
     */
    public Builder setRecord(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      record_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Holds the record data for getRecord
     * </pre>
     *
     * <code>string record = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecord() {
      record_ = getDefaultInstance().getRecord();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Holds the record data for getRecord
     * </pre>
     *
     * <code>string record = 1;</code>
     * @param value The bytes for record to set.
     * @return This builder for chaining.
     */
    public Builder setRecordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      record_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <pre>
     * Holds the size data for getSize
     * </pre>
     *
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <pre>
     * Holds the size data for getSize
     * </pre>
     *
     * <code>int32 size = 2;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Holds the size data for getSize
     * </pre>
     *
     * <code>int32 size = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      size_ = 0;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <pre>
     * Indicates success for addRecord operation
     * </pre>
     *
     * <code>bool success = 3;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <pre>
     * Indicates success for addRecord operation
     * </pre>
     *
     * <code>bool success = 3;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Indicates success for addRecord operation
     * </pre>
     *
     * <code>bool success = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000004);
      success_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RPC_Response)
  }

  // @@protoc_insertion_point(class_scope:RPC_Response)
  private static final io.grpc.dbserver.RPC_Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.dbserver.RPC_Response();
  }

  public static io.grpc.dbserver.RPC_Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RPC_Response>
      PARSER = new com.google.protobuf.AbstractParser<RPC_Response>() {
    @java.lang.Override
    public RPC_Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RPC_Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RPC_Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.dbserver.RPC_Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

