// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dbServer.proto
// Protobuf Java Version: 4.28.3

package io.grpc.dbserver;

public interface RPC_RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RPC_Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RPC_Request.Operation operation = 1;</code>
   * @return The enum numeric value on the wire for operation.
   */
  int getOperationValue();
  /**
   * <code>.RPC_Request.Operation operation = 1;</code>
   * @return The operation.
   */
  io.grpc.dbserver.RPC_Request.Operation getOperation();

  /**
   * <code>optional int32 Index = 2;</code>
   * @return Whether the index field is set.
   */
  boolean hasIndex();
  /**
   * <code>optional int32 Index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>optional string Record = 3;</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>optional string Record = 3;</code>
   * @return The record.
   */
  java.lang.String getRecord();
  /**
   * <code>optional string Record = 3;</code>
   * @return The bytes for record.
   */
  com.google.protobuf.ByteString
      getRecordBytes();
}
