// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dbServer.proto
// Protobuf Java Version: 4.28.3

package io.grpc.dbserver;

public final class DbServer {
  private DbServer() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      DbServer.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RPC_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPC_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RPC_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RPC_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016dbServer.proto\"\276\001\n\013RPC_Request\022)\n\toper" +
      "ation\030\001 \001(\0162\026.RPC_Request.Operation\022\022\n\005I" +
      "ndex\030\002 \001(\005H\000\210\001\001\022\023\n\006Record\030\003 \001(\tH\001\210\001\001\"F\n\t" +
      "Operation\022\013\n\007DEFAULT\020\000\022\016\n\nGET_RECORD\020\001\022\016" +
      "\n\nADD_RECORD\020\002\022\014\n\010GET_SIZE\020\003B\010\n\006_IndexB\t" +
      "\n\007_Record\"=\n\014RPC_Response\022\016\n\006record\030\001 \001(" +
      "\t\022\014\n\004size\030\002 \001(\005\022\017\n\007success\030\003 \001(\0102B\n\017Data" +
      "baseService\022/\n\020PerformOperation\022\014.RPC_Re" +
      "quest\032\r.RPC_ResponseB\024\n\020io.grpc.dbserver" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RPC_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RPC_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RPC_Request_descriptor,
        new java.lang.String[] { "Operation", "Index", "Record", });
    internal_static_RPC_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RPC_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RPC_Response_descriptor,
        new java.lang.String[] { "Record", "Size", "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
