// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dbServer.proto
// Protobuf Java Version: 4.28.3

package io.grpc.dbserver;

public interface RPC_ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RPC_Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Holds the record data for getRecord
   * </pre>
   *
   * <code>string record = 1;</code>
   * @return The record.
   */
  java.lang.String getRecord();
  /**
   * <pre>
   * Holds the record data for getRecord
   * </pre>
   *
   * <code>string record = 1;</code>
   * @return The bytes for record.
   */
  com.google.protobuf.ByteString
      getRecordBytes();

  /**
   * <pre>
   * Holds the size data for getSize
   * </pre>
   *
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <pre>
   * Indicates success for addRecord operation
   * </pre>
   *
   * <code>bool success = 3;</code>
   * @return The success.
   */
  boolean getSuccess();
}
